#!/usr/bin/env bash
# nftables firewall rules
# tried iptables first but nftables is what debian wants now apparently
set -euo pipefail

WAN_IFACE="${WAN_IFACE:-eth0}"
LAN_IFACE="${LAN_IFACE:-eth1}"
SSH_PORT="${SSH_PORT:-22}"
VPN_ENABLED="${VPN_ENABLED:-0}"

# make sure nobody passed us garbage interface names
validate_iface() {
  local name="$1" value="$2"
  if [[ ! "$value" =~ ^[a-zA-Z0-9_-]{1,15}$ ]]; then
    echo "[firewall] ERROR: Invalid ${name}: '${value}'"
    exit 1
  fi
}

validate_iface "WAN_IFACE" "$WAN_IFACE"
validate_iface "LAN_IFACE" "$LAN_IFACE"

if [[ ! "$SSH_PORT" =~ ^[0-9]{1,5}$ ]] || (( SSH_PORT < 1 || SSH_PORT > 65535 )); then
  echo "[firewall] ERROR: Invalid SSH_PORT: '${SSH_PORT}'"
  exit 1
fi

if [[ "$VPN_ENABLED" != "0" && "$VPN_ENABLED" != "1" ]]; then
  echo "[firewall] ERROR: VPN_ENABLED must be 0 or 1"
  exit 1
fi

echo "[firewall] Installing nftables..."
apt-get install -y -qq nftables

echo "[firewall] Writing ruleset (WAN=${WAN_IFACE}, LAN=${LAN_IFACE}, SSH=${SSH_PORT})..."

# build the vpn rules ahead of time so we dont have to do
# weird command substitution inside the heredoc
VPN_INPUT_RULE=""
VPN_FORWARD_RULE=""
VPN_NAT_RULE=""
if [[ "$VPN_ENABLED" == "1" ]]; then
  VPN_INPUT_RULE="    udp dport 51820 accept"
  VPN_FORWARD_RULE="    iif \$LAN oif wg0 accept"
  VPN_NAT_RULE="    oif wg0 masquerade"
fi

cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# generated by veilnet, dont edit by hand unless you know what youre doing
flush ruleset

define WAN = ${WAN_IFACE}
define LAN = ${LAN_IFACE}
define SSH_PORT = ${SSH_PORT}

table inet filter {

  # ports we allow in
  set allowed_tcp {
    type inet_service; flags constant;
    elements = { \$SSH_PORT, 80, 443, 53, 4711 }
  }

  chain input {
    type filter hook input priority 0; policy drop;

    # let existing connections through
    ct state established,related accept
    ct state invalid drop

    # localhost always ok
    iif lo accept

    # ping is fine
    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    # dns from lan to pihole
    iif \$LAN ip protocol { tcp, udp } th dport 53 accept
    iif lo ip protocol { tcp, udp } th dport 53 accept

    # our service ports
    tcp dport @allowed_tcp accept

    # mdns so veilnet.local works
    udp dport 5353 accept

    # wireguard if enabled
${VPN_INPUT_RULE}

    # log and drop everything else
    log prefix "veilnet-drop: " flags all counter drop
  }

  chain forward {
    type filter hook forward priority 0; policy drop;

    ct state established,related accept
    ct state invalid drop

    # let lan talk to the internet (or through the vpn)
    iif \$LAN oif \$WAN accept
${VPN_FORWARD_RULE}
  }

  chain output {
    type filter hook output priority 0; policy accept;
  }
}

# nat for inline mode
table ip nat {
  chain postrouting {
    type nat hook postrouting priority 100; policy accept;
    oif \$WAN masquerade
${VPN_NAT_RULE}
  }
}
EOF

# check the config before actually loading it
nft -c -f /etc/nftables.conf \
  && echo "[firewall] Ruleset validated." \
  || { echo "[firewall] ERROR: nftables config validation failed."; exit 1; }

systemctl enable --now nftables
nft -f /etc/nftables.conf

echo "[firewall] nftables active."
nft list ruleset | grep -c "accept\|drop" | xargs -I{} echo "[firewall] {} accept/drop rules loaded."
